### ISSUE TITLE
Volets

### ISSUE THREAD

**Issue by MarieHusseini** [OmegaT-L10N/fr#11]
Hello,

J'ai relu le fichier Windows_Aligner. J'y ai mis quelques notes, à checker.

Je vais enchaîner avec la partie "Volets".

**Comment by MarieHusseini** [comment]
Relecture de la partie "Volets" terminée.

J'ai tout mis sous forme de notes, je n'ai pas modifié directement les segments, pensant que les stagiaires repassaient derrière nous en tous les cas. Dites-moi ce qu'il convient de faire.

**Comment by brandelune** [comment]
Le mieux c'est d'intervenir directement dans le projet. Mais je pense que j'ai bien repris toutes tes notes.

**Comment by brandelune** [comment]
Donc je me permets de fermer le ticket.
