### ISSUE TITLE
mappage ?

### ISSUE THREAD

**Issue by brandelune** [OmegaT-L10N/fr#2]
@vbdx, Je comprends la signification et l'usage, mais est-ce que "mise en correspondance" ou quelque chose comme ça ne serait pas un peu plus lisible pour le traducteur non technique ?

**Comment by vbdx** [comment]
j'ai vérifié dans Antidote, Mappage est le bon terme : 

![Capture du 2021-01-29 14-49-56](https://user-images.githubusercontent.com/11272904/106283006-a8d72380-6241-11eb-8d03-adcd2f2179b1.png)

De plus, cette partie sur les projets en équipe concerne plutôt les administrateurs de projet que les traducteurs non techniques.

Mais si tu veux, on peut écrire : Mappage (mise en correspondance) du référentiel

**Comment by brandelune** [comment]
Oui, j'ai bien vu dans Antidote. J'ai penser garder mappage dans les rubriques et labels et expliciter avec "mise en correspondance" dans le texte.

**Comment by vbdx** [comment]
Oui, c'est bien de faire le distingo entre titres et corps de texte

**Comment by brandelune** [comment]
Parfait. Je fais comme ça, et je ferme l'issue :-)
