### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Nath-Kawette** [OmegaT-L10N/fr#9]
Je relis le fichier Introduction (Nathalie)

**Comment by Nath-Kawette** [comment]
segment 4542 (fichier Introduction) : Je vois une incohérence dans cet encadré grisé. Sur ce segment, soit le verbe devrait être à l'infinitif (comme sur le premier "bullet point"), soit il ne faut pas de "bullet point" (et dans ce cas il ne devrait y en avoir du tout et tous les verbes doivent être à l'infinitif?).

**Comment by Nath-Kawette** [comment]
Révision terminée pour l'Introduction.

**Comment by brandelune** [comment]
> segment 4542 (fichier Introduction) : Je vois une incohérence dans cet encadré grisé. Sur ce segment, soit le verbe devrait être à l'infinitif (comme sur le premier "bullet point"), soit il ne faut pas de "bullet point" (et dans ce cas il ne devrait y en avoir du tout et tous les verbes doivent être à l'infinitif?).

@ciri23 vous pouvez jeter un coup d'œil ?

**Comment by ciri23** [comment]
@Nath-Kawette Le segment 4542 apparaît dans le fichier Preferences (j'ai 72 fichiers au total). Pouvez-vous me donner le segment exact pour que je puisse effectuer une recherche textuelle ? Je pense qu'il y a un décalage dans la numérotation des segments.

**Comment by Nath-Kawette** [comment]
Il s'agit du fichier "Introduction", c'est un .doc (Rechercher les segments annotés? j'ai ajouté une "note" sur le 4542).
Je colle ci-dessous le texte brut -sans balises ni liens- de ce segment 4542. (Sur le rendu du manuel, la phrase apparaît dans un des encadrés intitulés "Note", sur fond gris clair ; il faut juste harmoniser les points présentés en "bullet point" pour que ce soit cohérent) :

Utilisez C + F pour filtrer les segments sur la base des critères que vous avez définis, et n'examinez que ceux-là.

**Comment by ciri23** [comment]
Merci, je l'ai retrouvé, mais pour moi, c'est le segment 2651 donc en effet, il y a un certain décalage.

Je suis d'accord avec vous donc je propose de laisser les deux "bullet point" et de simplement écrire le deuxième à l'infinitif.

**Comment by brandelune** [comment]
Est-ce qu'on peut fermer le ticket ?

**Comment by Nath-Kawette** [comment]
Oui ! (je pensais que mon pouce en l'air suffisait)

**Comment by brandelune** [comment]
> Oui ! (je pensais que mon pouce en l'air suffisait)

Haha ! Le pouce en l'air, quand il est humide, ça sert à prendre le sens du vent, mais autrement, il vaut mieux être explicite 😅
